PunktDe:
  NodeRestrictions:
    excludeRolesFromPackages:
      - Neos.Neos
      - Neos.Setup

Neos:
  Flow:
    aop:
      globalObjects:
        additionalUserInformation: PunktDe\NodeRestrictions\Service\UserService
